import gsap from 'gsap'
import Head from 'next/head'
import {useRef, useEffect} from 'react'
import Companies from '../components/Companies'
import Features from '../components/Features'
import Footer from '../components/Footer'
import Global from '../components/Global'
import Header from '../components/Header'
import Navbar from '../components/Navbar'
import Plans from '../components/Plans'
import Reviews from '../components/Reviews'
import Statistic from '../components/Statistic'
import Subscribe from '../components/Subscribe'
import styles from '../styles/Home.module.css'

export default function Home() {
  const tl = useRef(null);

  useEffect (() => {
    gsap.to('body', {css: {visibility: 'visible'}});

    tl.current = gsap.timeline()
      .from('.logo', {
        x: -100,
        opacity: -3,
        duration: 1,
        ease: 'power3.out'
      })
      .to('.links', {
        y: 0,
        opacity: 1,
        stagger: {
          amount: 1
        }
      })
      .to('.sign', {
        x: 0,
        opacity: 1,
        delay: -1,
        stagger: {
          amount: .5
        }
      })
      .to('.lefthead-h1', {
        opacity: 1,
        x: 0,
        y: 0,
        duration: .5,
        delay: 0,   
      })
      .from(".lefthead-p", {
        opacity: 0,
        y: 50,
      })
      .from(".lefthead-a", {
        opacity: 0,
      })
      .from('.header-illus', {
        opacity: 0,
        x: 100,
        y: 100,
        duration: .5,
        delay: 0,   
      })
      .from('.float', {
        opacity: 0,
        stagger: {
          amount: .5
        }
      })
  }, [])
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;700&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossOrigin="anonymous"></link>
      </Head>
      
      <Navbar/>
      <Header />
      <Statistic />
      <Features />
      <div className={styles.pricecontainer}>
        <Plans />
      </div>
      <Global />
      <Companies />
      <Reviews />
      <Subscribe />
      <div className={styles.footercontainer}>
        <Footer />
      </div>
    </div>
  )
}
